language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  # high_level_summary_instructions: ""
  poem: true
  review_status: true
  review_details: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "^dev$"
chat:
  auto_reply: true
