[package]
name = "blog-domain"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.79"
serde = { version = "1.0.197", features = ["derive"] }
