use serde::{Deserialize, Serialize};

// https://ai.google.dev/api/generate-content?hl=en#request-body
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GeminiRequest {
    pub system_instruction: SystemInstruction,
    pub contents: Vec<Content>,
}

#[derive(Debug, Serialize)]
pub struct SystemInstruction {
    pub parts: Vec<Part>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Content {
    pub parts: Vec<Part>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Part {
    pub text: String,
}

// https://ai.google.dev/api/generate-content?hl=en=#generatecontentresponse
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GeminiResponse {
    pub candidates: Vec<Candidate>,
    pub prompt_feedback: Option<PromptFeedback>,
}

#[derive(Debug, Deserialize)]
pub struct Candidate {
    pub content: Option<Content>,
    pub finish_reason: Option<FinishReason>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FinishReason {
    // Default value. This value is unused.
    FinishReasonUnspecified,
    Stop,
    MaxTokens,
    Safety,
    // The response candidate content was flagged for recitation reasons.
    Recitation,
    // The response candidate content was flagged for using an unsupported language.
    Language,
    Other,
    Blocklist,
    // 	Token generation stopped for potentially containing prohibited content.
    ProhibitedContent,
    // Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
    Spii,
    // The function call generated by the model is invalid.
    MalformedFunctionCall,
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PromptFeedback {
    pub block_reason: BlockReason,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum BlockReason {
    // Default value. This value is unused.
    BlockReasonUnspecified,
    // Prompt was blocked due to safety reasons.
    Safety,
    // Prompt was blocked due to unknown reasons.
    Other,
    // Prompt was blocked due to the terms which are included from the blocklist.
    Blocklist,
    // Prompt was blocked due to prohibited content.
    ProhibitedContent,
    #[serde(other)]
    Unknown,
}
