name: Build And Push Container Image

on:
  push:
    branches:
      - stg
    paths:
      - "blog-**/**"
      - "Docker/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ github.ref_name }}-my-blog-web-api
          tags: |
            type=sha,ref=latest
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/rust/Dockerfile
          push: true
          target: ${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          # secrets: |
          #   GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
